apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  components:
    - name: my-app
      type: microservice
      properties:
        accountId: ""
        image: 
        targetPort: 5001